### ISSUE TITLE
{{ qty_ordered }} gives empty value 

### ISSUE THREAD

**Issue by gokulavailable** [mageplaza/magento-2-webhook#54] opened 2020-12-14 11:46 UTC
Hi, We are sending the below data when ship event is happening,

```
{% for product in item.items %}
{
  "Product_Id": "{{ product.sku }}",
  "Product_Current_Stock": "{{ product.qty_ordered}}",
  "Product_Stock_Total_Price": "{{ product.price }}",
  "Branch_Id": "1",
  "Transaction_Id": "1",
  "DivisionId": "1"
}
{% if forloop.last == false %}
,
{% endif %}
{% endfor %}
```

The request was success but we qty_ordered sent as empty. Below is how the data sent,

```
{
  "Product_Id": "24-MB01",
  "Product_Current_Stock": "",
  "Product_Stock_Total_Price": "34.0000",
  "Branch_Id": "1",
  "Transaction_Id": "1",
  "DivisionId": "1"
}
```
Please let us know what could be reason.

**Comment by Shinichi69** [comment] 2020-12-15 03:42
Hi @gokulavailable 

I’m Shin from Mageplaza and I will support you on this issue.

To get the qty of the purchased product with the shipment hook, please use this variable:
- {{ product.qty }}

Please try again and let me know the result.

Thanks so much!

**Comment by gokulavailable** [comment] 2020-12-15 05:49
Thanks Lot It's Working fine.

**Comment by Shinichi69** [comment] 2020-12-15 06:48
Hi @gokulavailable 

Thanks for your response.

Since the issue is resolved, I will close this issue.

Thanks so much!

**Closed by Shinichi69** 2020-12-15 06:48 UTC
