### ISSUE TITLE
Not Auto Triggering in Magento 2.3.2

### ISSUE THREAD

**Issue by Spartaa** [mageplaza/magento-2-webhook#15] opened 2019-10-08 13:39 UTC
When I create new order the webhooks give me the error but when I go in logs and replay that hook again it runs successfully without any error.

Why is it happening? 
Please Help?
and also the logs are also not showing completely so I can identify whats the problem is

**Comment by Shinichi69** [comment] 2019-10-10 04:40
We checked it locally and did not encounter any errors as you mentioned.
Please describe the steps to reproduce your issue.

Thanks so much!

**Comment by Spartaa** [comment] 2019-10-10 06:33
I am facing this issue on the server 

From you extension


I created a hook new_order and set my Api path in payload
http://captain-staging.us-east-2.elasticbeanstalk.com/api/v1/order/SaveSourceData?order_id={{ item.entity_id }}

my method is PUT and then i select content and I am ready to go.

When I generate an order  it gives me an error  and when I go in logs which are not showing me complete only these lines


HTTP/1.1 500 Internal Server Error
Date: Thu, 10 Oct 2019 06:08:42 GMT
Server: Apache
Cache-Control: no-cache, private
X-RateLimit-Limit: 60
X-RateLimit-Remaining: 59
Connection: close
Content-Type: text/html; charset=UTF-8

<!doctype html>
<html class="theme-light">
<head>
    
    <style>
        pre.sf-dump {
            display: none !important;
        }
    </style>

    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="robots" content="noindex, nofollow">

    <title>


not more than that on live server

after this when I replay the log it is successfully run

**Comment by Shinichi69** [comment] 2019-10-11 10:05
I tried reproducing your problem on my local. However, I did not receive the error as you mentioned.

Please try again to see if your error appears again.

Thanks so much!

**Comment by Spartaa** [comment] 2019-10-11 10:30
I am working on sever and I am facing this issue still that when order
created it give me error but when I check in log and replay that it runs
successfully?
Should I  send video or something?

**Comment by Spartaa** [comment] 2019-10-11 10:52
this is my magento admin panel link in which  extension is installed.
http://qareeb-dev.us-east-2.elasticbeanstalk.com
 and my Api is on laravel 
http://captain-staging.us-east-2.elasticbeanstalk.com/api/v1/order/SaveSourceData??order_id={{ item.entity_id }}&customer_id={{ item.customer_id }}

**Comment by Shinichi69** [comment] 2019-10-14 02:15
Please send me a video about your issue or you can submit a ticket here:
https://mageplaza.freshdesk.com/support/tickets/new
and provide your SSH and admin credentials so I can check directly for you.

Thanks so much!

**Comment by Spartaa** [comment] 2019-10-15 05:51
https://drive.google.com/file/d/1oO4d4K3fXYcUci7G2jO1eWsWu6nJCeFn/view

This is the video of my problem

**Comment by Spartaa** [comment] 2019-10-15 05:58
which observer event is triggered when new order is created

**Comment by Shinichi69** [comment] 2019-10-15 08:35
Hi @Spartaa 

I can see your problem via video, but I cannot reproduce it locally.
Please create a ticket about your issue here:
https://mageplaza.freshdesk.com/support/tickets/new

And provide your SSH and admin credentials so I can check your issue directly.

Thanks so much!

**Comment by Shinichi69** [comment] 2019-10-15 08:56
Hi @Spartaa 

I saw the ticket you created, please provide the necessary information so I can check your issue.

Thanks so much!

**Comment by Spartaa** [comment] 2019-10-15 09:21
ok

**Comment by Shinichi69** [comment] 2019-10-30 08:11
Hi @Spartaa 

I didn't see your response to the ticket you created.
So please allow me to close this issue.
If there are any other issues, please contact us via your ticket.

Thanks so much!

**Closed by Shinichi69** 2019-10-30 08:11 UTC

**Comment by Spartaa** [comment] 2019-10-30 08:17
I replied you there actually error is not resolving

**Comment by KarthickSelvam** [comment] 2020-06-23 09:51
I'm also facing this issue, is this fixed?

**Comment by ikram-doorhub** [comment] 2020-06-23 12:04
> I'm also facing this issue, is this fixed?

no

**Comment by ikram-doorhub** [comment] 2020-06-23 12:05
after trying so much and wasted my time 
finally, I left this Magento useless

**Comment by Spartaa** [comment] 2020-06-23 12:09
> I'm also facing this issue, is this fixed?

No, it's not after wasting my so much time on Magento.
I decided to leave Magento and save me precious time

**Comment by KarthickSelvam** [comment] 2020-07-08 12:21
I found the solution to this, the New Order hook uses sales_order_save_after, on this webhook, if you try to access order entity synchronously, you would get this error, because the order is not yet created. i.e the Order is not yet available in api until the webhook call gets response. 
In Our case we created a new hook, with checkout submit event on which the order entity is available in synchronous to the webhook call..
